---
title: "Publications"
description: |
  Publications and Presentations
site: distill::distill_website
---

<head>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-0208BTGWKG"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0208BTGWKG');
</script>
</head>

```{css, echo = F}
d-title{
    display: none;
  }
```

## Publications

***In Press***

Roark, C. L, Paulon, G., Rebaudo, G., **McHaney, J. R.,** Sarkar, A., & Chandrasekaran, B.(in press). Individual differences in working memory impact the trajectory of non-native speech category learning. *PLOS ONE*.

Mukhopadhyay, M., **McHaney, J. R.,**, Chandrasekaran, B., Sarkar, A. (in press). Bayesian Semiparametric Longitudinal Inverse-Probit Mixed Models for Category Learning. *Psychometrika*.

***Peer-reviewed***

**McHaney, J. R.,** Schuerman, W. L., Leonard, M. K., & Chandrasekaran, B. (2023). Low amplitude transcutaneous auricular vagus nerve stimulation modulates performance but not pupil size during non-native speech category learning. *Journal of Speech, Language, and Hearing Research, 60*(10), 3825-3843.

Cancel, V. E.^ **, McHaney, J. R.**^, Milne, V. Palmer, C., & Parthasarathy, A. (2023). A data-driven approach to identify a rapid screener for auditory processing disorder testing referrals in adults. *Scientific Reports, 13*, 13636. (^co-lead authors).

Lescht, E., Venker, C., **McHaney, J. R.,** Bohland, J., & Hampton Wray, A. (2022). Novel Word Recognition in Childhood Stuttering. *Topics in Language Disorders, 42*(1), 41-56.

**McHaney, J. R.,** Tessmer, R., Roark, C. L., & Chandrasekaran, B. (2021). Working memory relates to individual differences in speech category learning: Insights from computational modeling and pupillometry. *Brain and Language, 222,* 105010.

**McHaney, J. R.,**  Gnanateja, G. N., Smayda, K. E., Zinszer, B. D., & Chandrasekaran, B. (2021). Cortical Tracking of Speech in Delta Band Relates to Individual Differences in Speech in Noise Comprehension in Older Adults. *Ear and Hearing, 42*(2), 343-354.

Llanos, F., **McHaney, J. R.,** Schuerman, W. L., Yi, H. G., Leonard, M. K., & Chandrasekaran, B. (2020). Non-invasive peripheral nerve stimulation selectively enhances speech category learning in adults. *npj Science of Learning, 5*(1), 1-11.

Koski, J. E., **McHaney, J. R.,**, Rigney, A. E., & Beer, J. S. (2020). Recondsidering Longstanding Assumptions About the Role of Medial Prefrontal Cortex (MPFC) in Social Evaluation. *NeuroImage, 214,* 116752.

***Archived Preprints***

**McHaney, J. R.,** Hancock, K. E., Polley, D. B., & Parthasarathy, A. (2023). Sensory representations and pupil-indexed listening effort provide complementary contributions to multi-talker speech intelligibility. *bioRxiv*. doi: <https://doi.org/10.1101/2023.08.13.553131>.

## Presentations

Parker, A., **McHaney, J. R.,** Coleman, B., Chandrasekaran, B., & Hampton Wray, A. (November 2023). Phonological Awareness and the Impact of Noise Level on Speech Perception. Poster to be presented at the 2023 American Speech-Language-Hearing Association Convention, Boston, MA.

Mitchell, C., Zink, M. E., **McHaney, J. R.,** Anthony, S., Hallihan, M., Chandrasekaran, B., & Parthasarathy, A. (April 2023). Relationship Between Altered Auditory Temporal Processing and Speech Perception in Noise With Age. Poster to be presented at the American Academy of Audiology 2023 + HearTECH Expo, Seattle, WA.

Yurasits, K., Zhen, L. Q., Parida, S., Klara, J., **McHaney, J. R.,** Cancel, V., Zink, M. E., Mitchell, C., Chandrasekaran, B., & Parthasarathy, A. (April 2023). Age-related changes in the representations of stimulus temporal fine structure cues and their relationship to multi-talker speech intelligibility. Poster to be presented at the American Academy of Audiology 2023 + HearTECH Expo, Seattle, WA.

**McHaney, J. R.,** & Chandrasekaran, B. (March 2023). Lexical knowledge facilitates phoneme categorization at intermediate noise levels. Poster presented at the American Auditory Society's 50th Annual Scientific & Technology Conference, Scottsdale, AZ.

Parker, A., **McHaney, J. R.,** Xie, Z., Chandrasekaran, B., & Hampton Wray, A. (February 2023). Cortical Tracking of Continuous Speech-in-Noise: Children's Use of Linguistic and Acoustic Information. Poster presented at the Association for Research in Otolaryngology 46th Annual MidWinter Meeting, Orlando, FL.

Zink, M. E., **McHaney, J. R.,** Mitchell, C., Hallihan, M., Anthony, S., Chandrasekaran, B., & Parthasarathy, A. (February 2023). Neurophysiological Markers of Sensory Gain and Their Relationship to Speech Perception in Noise in Young and Middle-aged Adults. Poster presented at the Association for Research in Otolaryngology 46th Annual MidWinter Meeting, Orlando, FL.

Zhen, L. Q., **McHaney, J. R.,** Zink, M. E., Mitchell, C., Parida, S., Anthony, S., Hallihan, M., Brown, C. A., Chandrasekaran, B., & Parthasarathy, A. (February 2023). Age-related Differences in Neural and Perceptual Signatures of Temporal Fine Structure Procesing Underlying Multi-talker Speech Intelligibility. Poster presented at the Association for Research in Otolaryngology 46th Annual MidWinter Meeting, Orlando, FL.

**McHaney, J. R.,** Zhen, L. Q., Anthony, S., Xie, Z., Parthasarathy, A., & Chandrasekaran, B. (February 2023). Deficits in Sensory Decision-Making Underlie Self-Perceived Hearing Difficulties. Talk presented at the Association for Research in Otolaryngology 46th Annual MidWinter Meeting, Orlando, FL.

**McHaney, J. R.,** Zhen, L. Q., Roark, C. L., Parthasarathy, A., & Chandrasekaran, B. (October 2022). Sensory Encoding and Decisionmaking in Speech Perception in Noise. Poster presented at the Fourteenth Annual Meeting of the Society for Neurobiology of Language, Philadelphia, PA.

**McHaney, J. R.,** Yurasits, K., Hancock, K. E., Polley, D. B., & Parthasarathy, A. (July 2022). Neurophysiological markers of central gain and their relationship to speech-in-noise intelligibility in normal-hearing listeners. Poster presented at the Auditory System Gordon Research Conference: Preventing Loss and Recovering Function of the Auditory System, Smithfield, RI.

Cancel, V. E., **McHaney, J. R.,** Milne, V., Palmer, C., & Parthasarathy, A. (April 2022). Hearing Difficulties with Normal Audiograms: Insights from the ADP Test Battery. Poster presented at the American Academy of Audiology 2022 + HearTECH Expo, St. Louis, MO.

Cancel, V. E., **McHaney, J. R.,** Milne, V., Palmer, C., & Parthasarathy, A. (February 2022). Hearing Difficulties with Normal Audiograms: Insights from the Auditory Processing Disorder Test Battery. Poster presented at the 45th Annual MidWinter Meeting of the Association for Research in Otolaryngology, Virtual.

**McHaney, J. R.,** Hancock, K. E., Polley, D. B., & Parthasarathy, A. (February 2022). Neurophysiological markers of central gain and their relationship to speech-in-noise intelligibility. Poster presented at the 45th Annual MidWinter Meeting of the Association for Research in Otolaryngology, Virtual.

Lescht, E., Venker, C., **McHaney, J. R.,** & Hampton Wray, A. (January 2021). Novel word learning in children who stutter. Poster presented at the 12th Oxford Dysfluency Conference, Virtual.

**McHaney, J. R.,** Schuerman, W. L., Leonard, M. K., & Chandrasekaran, B. (October 2020). Non-invasive peripheral nerve stimulation paired with speech sounds modulates pupillary responses and selectively enhances learning. Poster presented at the Twelfth Annual Meeting of the Society for Neurobiology of Language, Virtual.

**McHaney, J. R.,** Zinszer, B. D., Smayda, K. E., Xie, Z., & Chandrasekaran, B. (December 2018). Cortical entrainment to the speech envelope relates to speech comprehension in older adults under adverse listening conditions. Poster presented at the 12th Annual Aging Institute Research Day, Pittsburgh, PA.

Llanos, F., **McHaney, J. R.,** Leonard, M. K., Schuerman, W. L., Yi, H. G., & Chandrasekaran, B. (August 2018). Transcutaneous vagus nerve stimulation enhances non-native speech categorization. Poster presented at the 10th Annual Meeting of the Society for the Neurobiology of Language, Québec City, Québec, Canada.

**McHaney, J. R.,** Zinszer, B. D., Smayda, K. E., & Chandrasekaran, B. (March 2018). Effect of listening environment on cortical entrainment to continuous speech in older adults. Poster presented at the Cognitive Neuroscience Society 25th Annual Meeting, Boston, MA.

Smayda, K. E, **McHaney, J. R.,** & Chandrasekaran, B. (May 2017). Music Training for the Enhancement of Speech-In-Noise Processing in Older Adults. Poster presented at the Texas Leadership Luncheon, Austin, TX.

Koski, J. E., **Richardson, J. B.,** Rigney, A. E., & Beer, J. S. (April 2016). Too much information or warm fuzzy feelings? Understanding the role of MPFC in processing the self versus others. Poster presented at the Social and Affective Neuroscience (SANS) Annual Meeting, New York, NY. (Last name changed from Richardson to McHaney in 2017).

## Press

Science Daily. (2020). Non-invasive nerve stimulation boosts learning of foreign language sounds. [press release]. Retrieved from [https://www.sciencedaily.com/releases/2020/08/200806092437.htm](https://www.sciencedaily.com/releases/2020/08/200806092437.htm)

Psychology Today. (2020). Can Vagus Nerve Stimulation Improve How We Learn? [press release]. Retrieved from [https://www.psychologytoday.com/intl/blog/the-athletes-way/202008/can-vagus-nerve-stimulation-improve-how-we-learn](https://www.psychologytoday.com/intl/blog/the-athletes-way/202008/can-vagus-nerve-stimulation-improve-how-we-learn)

Inverse (2020). Scientists discover brain hack that improves language abilities by 13%. Retrieved from [https://www.inverse.com/innovation/neural-stimulation-language-device](https://www.inverse.com/innovation/neural-stimulation-language-device)

FACETS. (2019). Team-Based Science at its best. [press release]. Retrieved from [https://issuu.com/pittshrs/docs/facets_spring_19_pdf/28](https://issuu.com/pittshrs/docs/facets_spring_19_pdf/28)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

